export enum ArticleCategory {
  business = 'business',
  crime = 'crime',
  domestic = 'domestic',
  education = 'education',
  entertainment = 'entertainment',
  environment = 'environment',
  food = 'food',
  health = 'health',
  lifestyle = 'lifestyle',
  other = 'other',
  politics = 'politics',
  science = 'science',
  technology = 'technology',
  top = 'top',
  tourism = 'tourism',
  world = 'world',
}
